name: Build touchHLE

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  create: # for tags

env:
  CARGO_TERM_COLOR: always

jobs:
  build-osx:
    runs-on: macos-latest  
