name: Build touchHLE

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  create: # for tags

env:
  CARGO_TERM_COLOR: always

jobs:
  build-osx:
    runs-on: macos-latest  

    steps:  
      - name: Checkout touchHLE  
        shell: bash
        run: |
          mkdir -p "$GITHUB_WORKSPACE"  
          git clone https://github.com/j92580498-max/touchHLE "$GITHUB_WORKSPACE"  
          cd "$GITHUB_WORKSPACE"  
          git fetch origin "$GITHUB_REF"  
          git checkout "$GITHUB_SHA"
